/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rwleea' at '2016/8/22 下午 9:15' with Gradle 2.14
 *
 * @author Rwleea, @date 2016/8/22 下午 9:15
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
